name: dekornata_test
description: A Flutter project for Dekornata interview test.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.1
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  http: ^0.13.3
  injectable: ^1.4.1
  intl: ^0.17.0
  json_serializable: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  flutter_lints: ^1.0.4
  freezed: ^0.14.2
  injectable_generator: ^1.4.1

flutter:
  uses-material-design: true
